version: '3.8'

services:
  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - ./chat:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dev:1234@database:5432/dev
      - REDIS_URL=redis://redis:6379
    depends_on:
      - database
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dev:1234@database:5432/dev
      - REDIS_URL=redis://redis:6379
    depends_on:
      - database
      - redis

  coin:
    build:
      context: ./coin
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./coin:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dev:1234@database:5432/dev
      - REDIS_URL=redis://redis:6379
    depends_on:
      - database
      - redis

  login:
    build:
      context: ./login
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./login:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dev:1234@database:5432/dev
      - REDIS_URL=redis://redis:6379
    depends_on:
      - database
      - redis

  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./scheduler:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://dev:1234@database:5432/dev
      - REDIS_URL=redis://redis:6379
    depends_on:
      - database
      - redis

  database:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres-data:
