services:
  
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  nextapp:
    container_name: frontend
    image: nextapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000" 
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres-data:
